### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by ghost**
it's better to use = than echo, it's the same thing, there's no need to write echo everytime, when you just can replace it with equals sign

### CODE REVIEW

**Comment by samgranger** [comment]
If you are referring to <?=$variable?> I'd advise against this, since this isn't always turned on in PHP configurations.

**Comment by ghost** [comment]
yeah I mean it, well, you can turn :)

**Comment by FuzzyBearBTC** [comment]
@samgranger so you would suggest not using this as it would need something to be turned on in php and could affect some users here or is this just a setting that I would need to enable on my server then it would be fine?

**Comment by samgranger** [comment]
It could cause problems yes, you need short tags enabled in php.ini which isn't default.

**Pull request closed without merging**
