### PR TITLE
Green: Stats at the bottom

### PR DESCRIPTION
**Pull request by Hibero**
I added a stats table at the bottom and moved some things around. Stats
Include: Total Coins, Difficulty, Price, Total Blocks, PoS Blocks last
24/7d, PoW Blocks last 24/7d, PoS:PoW Ratio last 24h/7d, Connections

I did use some of mark-bls commits but kept the green theme. I am able to test my code now so I should be able to experiment with new ideas much faster.

This is how it looks.
capture5

I am working on a version that will also work on mark-bl's theme now.

### CODE REVIEW

**Comment by FuzzyBearBTC** [comment]
@Hibero having merged https://github.com/FuzzyBearBTC/PeercoinBlockExplorer/pull/18 i now have conflicts with this merge.. do you want to pull and resubmit... sorry did I pull the wrong one first?

**Comment by Hibero** [comment]
@FuzzyBearBTC, both of these were up to you to choose from. The black was a continuation of mark-bl's work and the green is the with the old layout.
Did you want mark's?

**Comment by FuzzyBearBTC** [comment]
@Hibero yeah I was undecided.. can we not have a button on the site somewhere that lets us change between the two.. i like the green cos it matches the peercoin.net but the black has a nice professional feel

**Comment by Hibero** [comment]
@FuzzyBearBTC hmm... We can stick with the black for now and I'll work on a link or button.

**Pull request closed without merging**
